#  Copyright 2022-Present Autor contributors
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
import logging
from dataclasses import dataclass
from lib2to3.fixes.fix_input import context
from typing import List, Optional

from autor.flow_configuration.activity_configuration import ActivityConfiguration
from autor.framework.activity_context import ActivityContext
from autor.framework.activity_property import ActivityProperty
from autor.framework.activity_property_information import ActivityPropertyInformation
from autor.framework.context import Context
from autor.framework.util import Util


@dataclass
class ActivityInformation:
    """
    Container for activity-related information.
    """
    id:str
    """ Unique identifier of the activity within flow. Generated by Autor framework. Human-readable.
    """
    name:str
    """ Activity name read from the Flow Configuration. If not provided, generated by Autor framework.
    Unique within the activity block. Human-readable.
    """
    type:str
    """ Activity type. The type is provided in the activity class implementation decorator and in the Flow Configuration
    file. The activity type is used bind together the activity implementation and configuration.
    """
    configuration:ActivityConfiguration
    """ Activity configuration as provided in the Flow Configuration file.
    """
    context:Optional[ActivityContext] = None
    """ Utility for reading and writing from/to internal activity context.
        None if the activity has not yet been instantiated by the framework.
    """
    run_id:Optional[str] = None
    """ UUID of the activity run. Generated by Autor framework.
        None if the activity has not yet been instantiated by the framework.
    """
    inputs:Optional[List[ActivityPropertyInformation]] = None
    """ Activity inputs are values that are fetched flow configuration, are generated by previous activities
    or flow (as inputs when staring the activity block, through extensions etc.). The inputs are made available
    to the activity through activity properties that are decorated with @input and @config.
    None if the activity has not yet been instantiated by the framework.
    """
    outputs:Optional[List[ActivityPropertyInformation]] = None
    """ Activity outputs are values that activity generates and makes available to the rest of the flow. The outputs
    are made available to the flow through activity properties that are decorated with @output
        None if the activity has not yet been instantiated by the framework.
    """
    status:Optional[str] = None
    """ The status of the activity. 
    None if the activity has not yet been instantiated by the framework.
    """
    exception:Optional[Exception] = None
    """ If an unhandled exception was caught by Autor framework during the activity run, the
    exception can be found here.
    """

    def print(self):
        logging.info(f"id:            {self.id}")
        logging.info(f"name:          {self.name}")
        logging.info(f"run_id:        {self.run_id}")
        logging.info(f"type:          {self.type}")
        logging.info(f"status:        {self.status}")
        logging.info(f"exception:     {self.exception}")
        logging.info(f"inputs:        {self.inputs}")
        logging.info(f"outputs:       {self.outputs}")
        logging.info(f"context:       {self.context}")






        raw_context = Context.get_context_dict()
        Util.print_dict(dict=raw_context,comment="FULL RAW CONTEXT",level="info")






        if self.context is None:
            logging.info(f"context:       {self.context}")
        else:
            ctx_dict = self.context.raw()
            Util.print_dict(dict=ctx_dict, comment="RAW CONTEXT", level='info')

        logging.info(f"configuration: {self.configuration}")
        Util.print_dict(self.configuration.configuration)


    #def __init__(self):






