#  Copyright 2022-Present Autor contributors
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
import logging
from dataclasses import dataclass
from lib2to3.fixes.fix_input import context
from typing import List, Optional, Dict

from autor.flow_configuration.activity_block_configuration import ActivityBlockConfiguration
from autor.flow_configuration.activity_configuration import ActivityConfiguration
from autor.framework.activity_block_context import ActivityBlockContext
from autor.framework.activity_context import ActivityContext
from autor.framework.activity_property import ActivityProperty
from autor.framework.activity_property_information import ActivityPropertyInformation
from autor.framework.constants import Mode, Status
from autor.framework.context import Context
from autor.framework.util import Util


@dataclass
class ActivityBlockInformation:
    """
    Container for activity block related information.
    """
    id: Optional[str] = None
    """ Unique identifier of the activity block within flow. Provided by the user in the Flow Configuration.
    Human-readable.
    """
    mode: Optional[Mode] = None
    """ The mode of the activity block. The mode is provided by the user when running the activity block.
    """
    configuration: Optional[Dict[str,str]] = None
    """ Activity block configuration as provided in the Flow Configuration file.
    """
    context: Optional[ActivityBlockContext] = None
    """ Utility for reading and writing from/to internal activity block context.
        None, if the activity block has not yet been instantiated.
    """
    run_id: Optional[str] = None
    """ UUID of the activity block run. Generated by Autor framework.
        None, if the activity block has not yet been instantiated by the framework.
    """
    status: Optional[Status] = None
    """ The status of the activity block. 
    None if the activity has not yet been instantiated by the framework.
    """
    exception: Optional[List[Exception]] = None
    """ Exceptions that have occurred in Autor.
    """

    def print(self):
        Util.print_header("",text="A C T I V I T Y   B L O C K   I N F O R M A T I O N", level='info')
        logging.info(f"id:            {self.id}")
        logging.info(f"mode:          {self.mode}")

        # ----------------- Configuration ---------------
        logging.info(f"configuration:")
        Util.print_dict(self.configuration, level='info')

        logging.info(f"run_id:        {self.run_id}")
        logging.info(f"status:        {self.status}")

        # ----------------- Context --------------------
        if self.context is None:
            logging.info(f"context:       {self.context}")
        else:
            logging.info(f"context:")
            Util.print_dict(dict=self.context, level='info')

        # ----------------- Exception --------------------
        logging.info(f"exception:     {self.exception}")





