---
flowId: exampleFlow

#--------------------   A C T I V I T Y   M O D U L E S   -----------------------#
activityModules:
  - example_activities

#---------------------   A C T I V I T Y   B L O C K S   -----------------------#
activityBlocks:

  typeExample:
    activities:
      - type: type-1
      - type: type-2







  configExample:
    activities:
      - type: configurable-person
        configuration:
          name: Alice
          age: 32
          message: Hello from configuration!
      - type: configurable-person
        configuration:
          name: Bob
          age: 65








  readOrWriteScore:
    activities:
      - type: score-consumer
      - type: score-producer
      - type: score-consumer







  calculateHighestScore:
    activities:
      - type: score-producer-and-consumer
        configuration:
          myScore: 5
      - type: score-producer-and-consumer
        configuration:
          myScore: 9
      - type: score-producer-and-consumer
        configuration:
          myScore: 2
      - type: score-producer-and-consumer
        configuration:
          myScore: 11





  statusExample:
    activities:
      - type: skipped-activity
      - type: successful-activity
      - type: exception-activity
      - type: skipped-activity
      - type: successful-activity
      - type: exception-activity




  fullFlowExample:
    beforeBlock:
      activities: # activities in this list are run before running the main activity block
        - type: empty
          name: BB1
        - type: empty
          name: BB2

    beforeActivity:
      activities: # activities in this list are run before EACH main activity
        - type: empty
          name: BA1
        - type: empty
          name: BA2

    activities: # main activities
      - type: empty
        name: MA1
      - type: empty
        name: MA2
      - type: empty
        name: MA3

    afterActivity:
      activities: # activities in this list are run after EACH main activity
        - type: empty
          name: AA1
        - type: empty
          name: AA2

    afterBlock:
      activities: # activities in this list are run after the main block has run
        - type: empty
          name: AB1
        - type: empty
          name: AB2








  printProperties:
    activities:
      - type: print-properties
      - type: print-properties
      - type: print-properties






  sequence:
    activities:
      - type: skipped-activity
        name: first
        continueOn:
          - SUCCESS
          - SKIPPED

      - type: successful-activity
        name: second
        runOn:
          activityStatus:
            first:
              - SUCCESS
              - SKIPPED
          continueOn:
            - SUCCESS

      - type: successful-activity
        name: third
        runOn:
          activityStatus:
            first:
              - SUCCESS
          continueOn:
            - SUCCESS

      - type: successful-activity
        name: fourth
        runOn:
          activityStatus:
            third:
              - SUCCESS








  exampleBlock:
    activities:
      - type: EXAMPLE
      - type: EXAMPLE
      - type: EXAMPLE

  block-with-worker:
    worker:
      resourceSetCapabilities:
        - capA
        - capB
    activities:
      - type: EXAMPLE

  print-state-name-extension-example:
    activities:
      - type: EXAMPLE
      - type: EXAMPLE






  callback-example:
    activities:
      - type: CALLBACK
        configuration:
          status: SUCCESS
      - type: CALLBACK
        configuration:
          status: SKIPPED
      - type: CALLBACK
        configuration:
          status: FAIL






