---
flowId: exampleFlow

#--------------------   A C T I V I T Y   M O D U L E S   -----------------------#
activityModules:
  - activities

#---------------------   A C T I V I T Y   B L O C K S   -----------------------#
activityBlocks:
  quickExample:
    activities:
      - type: HELLO_WORLD
      - type: HELLO_WORLD
      - type: HELLO_WORLD