---
flowId: echoFlow

#--------------------   A C T I V I T Y   M O D U L E S   -----------------------#
activityModules:
  - autor.echo.echo_activities

#---------------------   A C T I V I T Y   B L O C K S   -----------------------#
activityBlocks:

  echoBlock:
    activities:
      - type: ECHO
        configuration:
          name: "First"
      - type: ECHO
        configuration:
          name: "Second"
      - type: ECHO
        configuration:
          name: "Third"






  helloWorld:
    activities:
      - type: HELLO_WORLD
      - type: HELLO_WORLD
      - type: HELLO_WORLD

  hello:
    activities:
      - type: HELLO_NAME
        configuration:
          name: Alice

      - type: HELLO_NAME
        configuration:
          name: Bob

      - type: HELLO_NAME


  helloEveryone:
    activities:
      - type: HELLO_EVERYONE
        configuration:
          name: Alice

      - type: HELLO_EVERYONE
        configuration:
          name: Bob

      - type: HELLO_EVERYONE











  block-with-worker:
    worker:
      resourceSetCapabilities:
        - capA
        - capB
    activities:
      - type: EXAMPLE

  print-state-name-extension-example:
    activities:
      - type: EXAMPLE
      - type: EXAMPLE

  print-properties-example:
    activities:
      - type: PRINT
        configuration:
          param1: Hello
          param2: World
      - type: PRINT
        name: Second activity
        configuration:
          holidays:
            - Saturday
            - Sunday
      - type: PRINT

  full-flow-example:
    beforeBlock:
      activities: # activities in this list are run before running the main activity block
        - type: EMPTY
          name: BB1
        - type: EMPTY
          name: BB2

    beforeActivity:
      activities: # activities in this list are run before EACH main activity
        - type: EMPTY
          name: BA1
        - type: EMPTY
          name: BA2

    activities: # main activities
      - type: EMPTY
        name: A1
      - type: EMPTY
        name: A2
      - type: EMPTY
        name: A3

    afterActivity:
      activities: # activities in this list are run after EACH main activity
        - type: EMPTY
          name: AA1
        - type: EMPTY
          name: AA2

    afterBlock:
      activities: # activities in this list are run after the main block has run
        - type: EMPTY
          name: AB1
        - type: EMPTY
          name: AB2


  full-flow-example-without-names:
    beforeBlock:
      activities: # activities in this list are run before running the main activity block
        - type: EMPTY
        - type: EMPTY

    beforeActivity:
      activities: # activities in this list are run before EACH main activity
        - type: EMPTY
        - type: EMPTY

    activities: # main activities
      - type: EMPTY
      - type: EMPTY
      - type: EMPTY

    afterActivity:
      activities: # activities in this list are run after EACH main activity
        - type: EMPTY
        - type: EMPTY

    afterBlock:
      activities: # activities in this list are run after the main block has run
        - type: EMPTY
        - type: EMPTY


  callback-example:
    activities:
      - type: CALLBACK
        configuration:
          status: SUCCESS
      - type: CALLBACK
        configuration:
          status: SKIPPED
      - type: CALLBACK
        configuration:
          status: FAIL

  status-example:
    activities:
      - type: SKIPPED
      - type: SUCCESS
      - type: ERROR

  output-and-input-example:
    activities:
      - type: OUTPUT
      - type: INPUT

  output-and-input-example-with-names:
    activities:
      - type: OUTPUT
        name: ScoreGenerator
      - type: INPUT
        name: ScoreReceiver

  input-output-example:
    activities:
      - type: INPUT_OUTPUT
        configuration:
          myScore: 5
      - type: INPUT_OUTPUT
        configuration:
          myScore: 9
      - type: INPUT_OUTPUT
        configuration:
          myScore: 2
      - type: INPUT_OUTPUT
        configuration:
          myScore: 1111

  config-example:
    activities:
      - type: CONFIGURABLE
        configuration:
          name: Alice
          message: Hello!
      - type: CONFIGURABLE
        configuration:
          name: Bob

  type-example:
    activities:
      - type: TYPE 1
      - type: TYPE 2


  calculateMax:
    activities:
      - type: MAX
        configuration:
          val: 1
      - type: MAX
        configuration:
          val: 7
      - type: MAX
        configuration:
          val: 2
      - type: MAX
        configuration:
          val: 9

  #flow_id: example-flow

  #activityBlocks:

  example-blockdd:
    activities:
      - type: EXAMPLE
        configuration:
          greeting: Hello World!

      - type: EXAMPLE
        name: HEJ
        configuration:
          greeting: Good morning World!

      - type: EXAMPLE
        configuration:
          greeting: Good night World!

  example-blockJJJ:
    beforeBlock:
      activities:
        - activityType: EXAMPLE
        - activityType: EXAMPLE
          name: Hõej
        - activityType: EXAMPLE
    beforeActivity:
      activities:
        - activityType: EXAMPLE
        - activityType: EXAMPLE
          name: Piret
        - activityType: EXAMPLE

    activities:
      - activityType: EXAMPLE
      - activityType: EXAMPLE
        name: Jeerik
      - activityType: EXAMPLE

    afterActivity:
      activities:
        - activityType: EXAMPLE
        - activityType: EXAMPLE
          name: måstje
        - activityType: EXAMPLE

    afterBlock:
      activities:
        - activityType: EXAMPLE
        - activityType: EXAMPLE
          name: måstje intje
        - activityType: EXAMPLE

  example-block3:
    activities:
      - activityType: EXAMPLE
        configuration:
          greeting: Hello World!

      - activityType: EXAMPLE
        configuration:
          greeting: Good morning World!

      - activityType: EXAMPLE
        configuration:
          greeting: Good night World!
